pipeline {
    agent any

    environment {
        FRONTEND_HOST = '10.0.1.206'
        BACKEND_HOST  = '10.0.2.58'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Deploy Backend') {
            steps {
                sshagent(credentials: ['aws-3tier-key']) {
                    sh """
                        scp -o StrictHostKeyChecking=no backend/app.py ubuntu@${BACKEND_HOST}:/var/www/backend/app.py
                        ssh -o StrictHostKeyChecking=no ubuntu@${BACKEND_HOST} 'sudo systemctl restart backend'
                    """
                }
            }
        }

        stage('Deploy Frontend') {
            steps {
                sshagent(credentials: ['aws-3tier-key']) {
                    sh """
                        scp -o StrictHostKeyChecking=no frontend/app.py ubuntu@${FRONTEND_HOST}:/var/www/frontend/app.py
                        scp -o StrictHostKeyChecking=no -r frontend/templates ubuntu@${FRONTEND_HOST}:/var/www/frontend/
                        ssh -o StrictHostKeyChecking=no ubuntu@${FRONTEND_HOST} 'sudo systemctl restart frontend'
                    """
                }
            }
        }
    }

    post {
        success {
            echo 'Deployment successful!'
        }
        failure {
            echo 'Deployment failed.'
        }
    }
}
